set(OMEGA_SKIP_CIME TRUE CACHE BOOL "")
set(OMEGA_C_COMPILER "mpiicx" CACHE STRING "")
set(OMEGA_CXX_COMPILER "mpiicpx" CACHE STRING "")
set(OMEGA_SYCL_COMPILER "mpiicpx" CACHE STRING "")
set(OMEGA_Fortran_COMPILER "mpiifx" CACHE STRING "")

set(CMAKE_C_FLAGS "-g --gcc-toolchain=$ENV{GCC_ROOT}" CACHE STRING "")
set(OMEGA_CXX_FLAGS "-g --gcc-toolchain=$ENV{GCC_ROOT} -Xclang -mlong-double-64" CACHE STRING "")
set(OMEGA_ARCH SYCL CACHE STRING "")
set(Kokkos_ARCH_NATIVE ON CACHE BOOL "")
set(Kokkos_ARCH_INTEL_GEN ON CACHE BOOL "")
set(Kokkos_ENABLE_ONEDPL OFF CACHE BOOL "")

set(OMEGA_GKLIB_ROOT "$ENV{HOME}/installs/gklib" CACHE STRING "")
set(OMEGA_METIS_ROOT "$ENV{HOME}/installs/metis" CACHE STRING "")
set(OMEGA_PARMETIS_ROOT "$ENV{HOME}/installs/parmetis" CACHE STRING "")

set(OMEGA_VECTOR_LENGTH 1 CACHE STRING "")

set(OMEGA_MPI_EXEC srun CACHE STRING "")
set(OMEGA_BUILD_TEST ON CACHE BOOL "")

set(NetCDF_PATH $ENV{NETCDF_C_ROOT} CACHE STRING "")
set(PnetCDF_PATH $ENV{PARALLEL_NETCDF_ROOT} CACHE STRING "")

set(OMEGA_USE_CALIPER ON CACHE BOOL "")
set(caliper_DIR $ENV{HOME}/installs/caliper/share/cmake/caliper CACHE STRING "")
