set(OMEGA_CIME_MACHINE chrysalis CACHE STRING "")
set(OMEGA_CIME_COMPILER gnu CACHE STRING "")
set(OMEGA_BUILD_TYPE Release CACHE STRING "")
set(OMEGA_BUILD_TEST ON CACHE BOOL "")
set(OMEGA_PARMETIS_ROOT /lcrc/soft/climate/polaris/chrysalis/spack/dev_polaris_0_4_0_gnu_openmpi/var/spack/environments/dev_polaris_0_4_0_gnu_openmpi/.spack-env/view CACHE STRING "")
