set(OMEGA_SKIP_CIME TRUE CACHE BOOL "")
set(OMEGA_C_COMPILER "mpiicc" CACHE STRING "")
set(OMEGA_CXX_COMPILER "mpiicpc" CACHE STRING "")
set(OMEGA_Fortran_COMPILER "mpiifort" CACHE STRING "")

set(CMAKE_C_FLAGS "-g" CACHE STRING "")
set(OMEGA_CXX_FLAGS "-g" CACHE STRING "")
set(OMEGA_ARCH SERIAL CACHE STRING "")
set(Kokkos_ARCH_NATIVE ON CACHE BOOL "")

set(OMEGA_GKLIB_ROOT "$ENV{HOME}/installs/gklib" CACHE STRING "")
set(OMEGA_METIS_ROOT "$ENV{HOME}/installs/metis" CACHE STRING "")
set(OMEGA_PARMETIS_ROOT "$ENV{HOME}/installs/parmetis" CACHE STRING "")

set(OMEGA_VECTOR_LENGTH 4 CACHE STRING "")
set(OMEGA_FUSED_VELTEND OFF CACHE BOOL "")
set(OMEGA_FUSED_ACCUM OFF CACHE BOOL "")

set(OMEGA_MPI_EXEC srun CACHE STRING "")
set(OMEGA_BUILD_TEST ON CACHE BOOL "")

set(NetCDF_PATH $ENV{NETCDF_C_ROOT} CACHE STRING "")
set(PnetCDF_PATH $ENV{PARALLEL_NETCDF_ROOT} CACHE STRING "")

set(OMEGA_USE_CALIPER ON CACHE BOOL "")
set(caliper_DIR $ENV{HOME}/installs/caliper/share/cmake/caliper CACHE STRING "")
