set(OMEGA_CIME_MACHINE pm-cpu CACHE STRING "")
set(OMEGA_CIME_COMPILER nvidia CACHE STRING "")
set(OMEGA_BUILD_TYPE Release CACHE STRING "")
set(OMEGA_BUILD_TEST ON CACHE BOOL "")
set(OMEGA_PARMETIS_ROOT /global/cfs/cdirs/e3sm/software/polaris/pm-cpu/spack/dev_polaris_0_3_0_nvidia_mpich/var/spack/environments/dev_polaris_0_3_0_nvidia_mpich/.spack-env/view CACHE STRING "")
