set(OMEGA_CIME_MACHINE pm-cpu CACHE STRING "")
set(OMEGA_CIME_COMPILER intel CACHE STRING "")
set(OMEGA_BUILD_TYPE Release CACHE STRING "")
set(OMEGA_BUILD_TEST ON CACHE BOOL "")
set(OMEGA_PARMETIS_ROOT /global/cfs/cdirs/e3sm/software/polaris/pm-cpu/spack/dev_polaris_0_3_0_intel_mpich/var/spack/environments/dev_polaris_0_3_0_intel_mpich/.spack-env/view CACHE STRING "")
