set(CMAKE_C_COMPILER mpicc CACHE STRING "")
set(CMAKE_CXX_COMPILER mpic++ CACHE STRING "")
set(CMAKE_Fortran_COMPILER mpifort CACHE STRING "")

set(OMEGA_C_COMPILER ${CMAKE_C_COMPILER} CACHE STRING "")
set(OMEGA_CXX_COMPILER ${CMAKE_CXX_COMPILER} CACHE STRING "")
set(OMEGA_Fortran_COMPILER ${CMAKE_Fortran_COMPILER} CACHE STRING "")

set(OMEGA_MPI_EXEC mpirun CACHE STRING "")

set(OMEGA_GKLIB_ROOT "/Users/mwarusz/omega/gklib" CACHE STRING "")
set(OMEGA_METIS_ROOT "/Users/mwarusz/omega/metis" CACHE STRING "")
set(OMEGA_PARMETIS_ROOT "/Users/mwarusz/omega/parmetis" CACHE STRING "")

set(OMEGA_BUILD_TEST ON CACHE BOOL "")
