set(OMEGA_SKIP_CIME TRUE CACHE BOOL "")
set(OMEGA_C_COMPILER "mpicc" CACHE STRING "")
set(OMEGA_CXX_COMPILER "mpicxx" CACHE STRING "")
set(OMEGA_Fortran_COMPILER "mpifort" CACHE STRING "")

set(OMEGA_CXX_FLAGS "-g -march=native" CACHE STRING "")
set(OMEGA_ARCH SERIAL CACHE STRING "")
#set(Kokkos_ARCH_NATIVE ON CACHE BOOL "")

set(OMEGA_GKLIB_ROOT "/Users/mwarusz/omega/gklib" CACHE STRING "")
set(OMEGA_METIS_ROOT "/Users/mwarusz/omega/metis" CACHE STRING "")
set(OMEGA_PARMETIS_ROOT "/Users/mwarusz/omega/parmetis" CACHE STRING "")

set(OMEGA_VECTOR_LENGTH 2 CACHE STRING "")
set(OMEGA_FUSED_VELTEND OFF CACHE BOOL "")
set(OMEGA_FUSED_ACCUM OFF CACHE BOOL "")

set(OMEGA_MPI_EXEC srun CACHE STRING "")
set(OMEGA_BUILD_TEST ON CACHE BOOL "")

set(OMEGA_USE_CALIPER ON CACHE BOOL "")
set(caliper_DIR $ENV{HOME}/installs/caliper/share/cmake/caliper CACHE STRING "")
