set(CMAKE_Fortran_COMPILER mpifort CACHE STRING "")
set(CMAKE_C_COMPILER       mpicc  CACHE STRING "")
set(CMAKE_CXX_COMPILER     mpic++  CACHE STRING "")

set(CMAKE_BUILD_TYPE     Release  CACHE STRING "")
set(CMAKE_Fortran_FLAGS_RELEASE     "-march=native -O3 -DNDEBUG"  CACHE STRING "")

set(ENABLE_HORIZ_OPENMP OFF CACHE BOOL "")
set(ENABLE_COLUMN_OPENMP OFF CACHE BOOL "")

set(USE_QUEUING OFF CACHE BOOL "")

set(BUILD_HOMME_SWEQX         ON CACHE  BOOL "")
set(BUILD_HOMME_PREQX         OFF CACHE BOOL "")
set(BUILD_HOMME_THETA         OFF CACHE BOOL "")
set(BUILD_HOMME_THETA_KOKKOS  OFF CACHE BOOL "")
set(BUILD_HOMME_PREQX_ACC     OFF CACHE BOOL "")
set(BUILD_HOMME_PREQX_KOKKOS  OFF CACHE BOOL "")
set(BUILD_HOMME_SWIM          OFF CACHE BOOL "")
set(BUILD_HOMME_PRIM          OFF CACHE BOOL "")
set(HOMME_ENABLE_COMPOSE      OFF CACHE BOOL "")

set(HOMME_FIND_BLASLAPACK      ON CACHE BOOL "")

SET(NETCDF_DIR $ENV{NETCDF_C_ROOT}  CACHE FILEPATH "")
SET(PNETCDF_DIR $ENV{PARALLEL_NETCDF_ROOT}  CACHE FILEPATH "")

SET (NetCDF_C_PATH $ENV{NETCDF_C_ROOT}  CACHE FILEPATH "")
SET (NetCDF_Fortran_PATH $ENV{NETCDFF_ROOT}  CACHE FILEPATH "")
