set(CMAKE_Fortran_COMPILER ftn CACHE STRING "")
set(CMAKE_C_COMPILER       cc  CACHE STRING "")
set(CMAKE_CXX_COMPILER     CC  CACHE STRING "")

set(CMAKE_BUILD_TYPE     Release  CACHE STRING "")
set(CMAKE_Fortran_FLAGS_RELEASE     "-march=native -O3 -DNDEBUG"  CACHE STRING "")

set(ENABLE_HORIZ_OPENMP OFF CACHE BOOL "")
set(ENABLE_COLUMN_OPENMP OFF CACHE BOOL "")

set(USE_QUEUING OFF CACHE BOOL "")

SET(CPRNC_DIR /global/cfs/cdirs/e3sm/tools/cprnc CACHE FILEPATH "")

set(BUILD_HOMME_SWEQX         ON CACHE  BOOL "")
set(BUILD_HOMME_PREQX         OFF CACHE BOOL "")
set(BUILD_HOMME_THETA         OFF CACHE BOOL "")
set(BUILD_HOMME_THETA_KOKKOS  OFF CACHE BOOL "")
set(BUILD_HOMME_PREQX_ACC     OFF CACHE BOOL "")
set(BUILD_HOMME_PREQX_KOKKOS  OFF CACHE BOOL "")
set(BUILD_HOMME_SWIM          OFF CACHE BOOL "")
set(BUILD_HOMME_PRIM          OFF CACHE BOOL "")
set(HOMME_ENABLE_COMPOSE      OFF CACHE BOOL "")

set(HOMME_FIND_BLASLAPACK      ON CACHE BOOL "")

SET(NETCDF_DIR $ENV{CRAY_NETCDF_HDF5PARALLEL_PREFIX} CACHE FILEPATH "")
SET(PNETCDF_DIR $ENV{CRAY_PARALLEL_NETCDF_DIR} CACHE FILEPATH "")
SET(HDF5_DIR $ENV{CRAY_HDF5_PARALLEL_PREFIX} CACHE FILEPATH "")

SET (NetCDF_C_PATH $ENV{CRAY_NETCDF_HDF5PARALLEL_PREFIX} CACHE FILEPATH "")
SET (NetCDF_Fortran_PATH $ENV{CRAY_NETCDF_HDF5PARALLEL_PREFIX} CACHE FILEPATH "")
